title: "Florent Forest"
author: "Florent Forest"
status: "PhD in Computer Science | Data & Machine learning scientist"
email: "f@florentfo.rest"
description: "Personal site"
permalink: /:title/
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - index.md
  - about.md
  - blog.md
  - research.md
  - publications.md
  - teaching.md
  - contact.md

icons:                      # icons in the header, see http://fontawesome.com/icons
 envelope: "mailto:f@florentfo.rest"
 github: "https://github.com/FlorentF9"
 linkedin: "https://www.linkedin.com/in/florent-forest"
 google-scholar: "https://scholar.google.fr/citations?user=vw7dDG0AAAAJ"
 researchgate: "https://www.researchgate.net/profile/Florent-Forest-2"
#  dblp: "https://dblp.uni-trier.de/pers/hd/f/Forest:Florent"

comments:                    # embed disqus or isso comments
  disqus: true
  disqus_shortname: "florentforest"
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
 - liquid-md5

sass:
  sass_dir: _sass
